//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur10eRg2Moveit
{
    [Serializable]
    public class HarvestPoseRequest : Message
    {
        public const string k_RosMessageName = "ur10e_rg2_moveit/HarvestPose";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg target_pose;
        public double gripper_position;

        public HarvestPoseRequest()
        {
            this.target_pose = new Geometry.PoseMsg();
            this.gripper_position = 0.0;
        }

        public HarvestPoseRequest(Geometry.PoseMsg target_pose, double gripper_position)
        {
            this.target_pose = target_pose;
            this.gripper_position = gripper_position;
        }

        public static HarvestPoseRequest Deserialize(MessageDeserializer deserializer) => new HarvestPoseRequest(deserializer);

        private HarvestPoseRequest(MessageDeserializer deserializer)
        {
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.gripper_position);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_pose);
            serializer.Write(this.gripper_position);
        }

        public override string ToString()
        {
            return "HarvestPoseRequest: " +
            "\ntarget_pose: " + target_pose.ToString() +
            "\ngripper_position: " + gripper_position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
